url: "https://practical-bhaskara-068d05.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl:  # the subpath of your site, e.g. /blog
title: "JC's essays" # the name of your site, e.g. ACME Corp.
